# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InsarExplorerDockWidget
                                 A QGIS plugin
 InSAR Explorer is a QGIS plugin that allows for dynamic visualization and analysis of InSAR time series data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-01
        git sha              : $Format:%H$
        copyright            : (C) 2024-2026 by Mahmud Haghighi
        email                : insar-explorer@eodeck.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

from .src.ui.time_series import TimeSeriesPointPanel

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'insar_explorer_dockwidget_base.ui'))


class InsarExplorerDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(InsarExplorerDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self._configure_workspace_layout()

    def _configure_workspace_layout(self):
        """Create independent Settings, Plot, and Points sibling regions."""
        self.time_series_point_panel = TimeSeriesPointPanel(self.splitter)
        self.splitter.addWidget(self.time_series_point_panel)
        for button in self.time_series_point_panel.selection_buttons:
            setattr(self, button.objectName(), button)

        self.settings_panel_region = self.widget_temporal_uw_btemp_plot_2
        self.time_series_workspace_region = self.widget_temporal_uw_bperp_plot_2
        self.settings_panel_region.setObjectName("settings_panel_region")
        self.time_series_workspace_region.setObjectName("time_series_workspace_region")
        self.widget_temporal_uw_btemp_plot_2.setMinimumWidth(220)
        self.widget_temporal_uw_btemp_plot_2.setMaximumWidth(330)
        self.scrollArea.setMaximumWidth(330)
        self.tab_config_panel.setMaximumWidth(320)

        self.splitter.setCollapsible(0, False)
        self.splitter.setCollapsible(1, False)
        self.splitter.setCollapsible(2, False)
        self.splitter.setStretchFactor(0, 0)
        self.splitter.setStretchFactor(1, 1)
        self.splitter.setStretchFactor(2, 0)
        self.splitter.setSizes([280, 700, TimeSeriesPointPanel.PREFERRED_WIDTH])

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
