# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InsarExplorerDockWidget
                                 A QGIS plugin
 InSAR Explorer is a QGIS plugin that allows for dynamic visualization and analysis of InSAR time series data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-01
        git sha              : $Format:%H$
        copyright            : (C) 2024-2026 by Mahmud Haghighi
        email                : insar-explorer@eodeck.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

from .src.ui.map_settings import MapSettingsPanel
from .src.ui.time_series import TimeSeriesPointPanel
from .src.ui.workspace_header import create_workspace_panel_header
from .src.ui.spacing import SPACE_XS, SPACE_SM, SPACE_LG
from .src.ui.splitter_state import (
    collapse_side_panel_sizes,
    expand_side_panel_sizes,
)

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'insar_explorer_dockwidget_base.ui'))


class InsarExplorerDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(InsarExplorerDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self._configure_workspace_layout()

    def _configure_workspace_layout(self):
        """Create independent Settings, Plot, and Points sibling regions."""
        self.map_settings_panel = MapSettingsPanel(self.splitter)
        self.splitter.insertWidget(0, self.map_settings_panel)
        self.settings_panel_region = self.map_settings_panel
        self.settings_panel = self.map_settings_panel
        for widget in self.map_settings_panel.compatibility_widgets:
            setattr(self, widget.objectName(), widget)

        self.time_series_point_panel = TimeSeriesPointPanel(self.splitter)
        self.splitter.addWidget(self.time_series_point_panel)
        for button in self.time_series_point_panel.selection_buttons:
            setattr(self, button.objectName(), button)

        self.time_series_workspace_region = self.widget_temporal_uw_bperp_plot_2
        self.time_series_workspace_region.setObjectName("time_series_workspace_region")
        self.time_series_panel_header = create_workspace_panel_header(
            self.time_series_workspace_region,
            "Time series",
            "label_time_series_panel",
        )
        self.verticalLayout_7.setContentsMargins(SPACE_LG, SPACE_SM, SPACE_LG, SPACE_LG)
        self.verticalLayout_7.setSpacing(SPACE_XS)
        self.verticalLayout_7.insertWidget(0, self.time_series_panel_header)

        self.splitter.setCollapsible(0, False)
        self.splitter.setCollapsible(1, False)
        self.splitter.setCollapsible(2, False)
        self.splitter.setStretchFactor(0, 0)
        self.splitter.setStretchFactor(1, 1)
        self.splitter.setStretchFactor(2, 0)
        initial_sizes = [
            MapSettingsPanel.PREFERRED_WIDTH,
            700,
            TimeSeriesPointPanel.PREFERRED_WIDTH,
        ]
        self.splitter.setSizes(initial_sizes)
        self._expanded_side_panel_widths = {
            0: initial_sizes[0],
            2: initial_sizes[2],
        }
        self.map_settings_panel.collapse_button.clicked.connect(
            lambda: self._sync_side_panel_splitter(
                0, self.map_settings_panel, self.map_settings_panel._collapsed
            )
        )
        self.time_series_point_panel.collapse_button.clicked.connect(
            lambda: self._sync_side_panel_splitter(
                2,
                self.time_series_point_panel,
                self.time_series_point_panel._collapsed,
            )
        )

    def _collapsed_panel_width(self, panel):
        """Return the compact chevron-rail width for a collapsed side panel."""
        return panel.collapse_button.sizeHint().width() + (1 * SPACE_XS)

    def _set_side_panel_collapsed_width(self, panel, collapsed_width):
        """Constrain an outer splitter child to its compact collapsed rail."""
        panel.setMinimumWidth(collapsed_width)
        panel.setMaximumWidth(collapsed_width)

    def _restore_side_panel_width_constraints(self, panel):
        """Restore normal outer-shell width constraints after expansion."""
        panel.setMinimumWidth(0)
        panel.setMaximumWidth(panel.MAXIMUM_WIDTH)

    def _sync_side_panel_splitter(self, index, panel, collapsed):
        """Transfer side-panel width to/from Time Series without touching state."""
        sizes = self.splitter.sizes()
        if len(sizes) != 3:
            return

        current_width = sizes[index]
        if collapsed:
            collapsed_width = self._collapsed_panel_width(panel)
            if current_width > collapsed_width:
                self._expanded_side_panel_widths[index] = current_width
            self._set_side_panel_collapsed_width(panel, collapsed_width)
            sizes = collapse_side_panel_sizes(sizes, index, collapsed_width)
        else:
            self._restore_side_panel_width_constraints(panel)
            target_width = self._expanded_side_panel_widths.get(
                index, panel.PREFERRED_WIDTH
            )
            sizes = expand_side_panel_sizes(sizes, index, target_width)

        self.splitter.setSizes(sizes)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
